name: animated-octo-palm-tree

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make some files
      run: echo `date` > date.txt

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
      
    - name: install pytest
      run: pip install pytest
      
    - name: python tests
      run:  ls

    - name: emacs
      uses: purcell/setup-emacs@master

    - name: Run tests
      run: which emacs
