name: animated-octo-palm-tree

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: purcell/setup-emacs@master
      with:
        version: snapshot
      
    - name: make some files
      run: echo `date` > date.txt

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
      
    - name: install pytest
      uses: actions/checkout@v2
      run: pip install pytest
      
    - name: python tests
      run:  pytest

        
    - name: Run tests
      run: which emacs; emacs --version
